GET http://localhost:8081/users

###

GET http://localhost:8081/users/6430d27d3a9cee54f27108dd

###
DELETE http://localhost:8081/users/6430d3ce666525288d20c51b

###
POST http://localhost:8081/users
Content-Type: application/json

{
"name" : "Maria",
"idade" : 34,
"email" : "fafa43@ig.com.br",
"password" : "fefefe33",
"incremento" : "33"
}

###
PATCH http://localhost:8081/users/6430d27d3a9cee54f27108dd
Content-Type: application/json

{
"password" : "paranga44",
"incremento" : "222"
}