GET http://localhost:8081/users

###

GET http://localhost:8081/users/6430d27d3a9cee54f27108dd

###
DELETE http://localhost:8081/users/6432132552e1ee9fbc8ccba5

###
POST http://localhost:8081/users/register
Content-Type: application/json

{
"name" : "Thales Pinto",
"idade" : 34,
"email" : "pinto@ig.com.br",
"password" : "pinto",
"incremento" : "33"
}

###
PATCH http://localhost:8081/users/643c829fde4fa95395758b6b
Content-Type: application/json

{
"password" : "paranga433334",
"incremento" : "222"
}

###

POST http://localhost:8081/users/login
Content-Type: application/json

{
"email" : "pinto@ig.com.br",
"password" : "pinto"
}