import Head from 'next/head';
import styles from './layout.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { UserContext } from '@/contexts/UserContext';
import { useContext } from 'react';

export default function Layout({ children, home }) {
  const router = useRouter();
  const { data } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Projeto Insulina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.header}>
        <Link href={`/`}>
          <h1 className={styles.header__logo}>Projeto insulina</h1>
        </Link>
        <nav>
          <ul className={styles.navbar}>
            <li className={styles.listItem}>
              {data ? (
                <Link href={'/dash'}> {data.email} </Link>
              ) : (
                <Link
                  className={
                    router.pathname == '/cadastro' ? styles.link__active : ''
                  }
                  href={`/cadastro`}
                >
                  Cadastro
                </Link>
              )}
            </li>
            <li className={styles.listItem}>
              {data ? (
                <Link
                  href={`/conta`}
                  className={
                    router.pathname == '/conta' ? styles.link__active : ''
                  }
                >
                  Conta
                </Link>
              ) : (
                <Link
                  href={`/login`}
                  className={
                    router.pathname == '/login' ? styles.link__active : ''
                  }
                >
                  Login
                </Link>
              )}
            </li>
          </ul>
        </nav>
      </header>
      <main>{children}</main>
      <footer className={styles.footer}>
        <p>
          Este projeto foi desenvolvido por João Fernando Paulin Quattrucci para
          fins de estudo utilizando as tecnologias React com NextJS.
        </p>
      </footer>
    </>
  );
}
