import Head from 'next/head';
import styles from './layout.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Layout({ children, home }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Projeto Insulina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.header}>
        <Link href={`/`}>
          <h1 className={styles.header__logo}>Projeto insulina</h1>
        </Link>
        <navbar>
          <ul className={styles.navbar}>
            <li className={styles.listItem}>
              <Link
                className={
                  router.pathname == '/cadastro' ? styles.link__active : ''
                }
                href={`/cadastro`}
              >
                Cadastro
              </Link>
            </li>
            <li className={styles.listItem}>
              <Link
                href={`/login`}
                className={
                  router.pathname == '/login' ? styles.link__active : ''
                }
              >
                Login
              </Link>
            </li>
          </ul>
        </navbar>
      </header>
      <main>{children}</main>
      <footer className={styles.footer}>
        <p>
          Este projeto foi desenvolvido por João Fernando Paulin Quattrucci para
          fins de estudo utilizando as tecnologias React com NextJS.
        </p>
      </footer>
    </>
  );
}
