import Head from 'next/head';
import styles from './layout.module.css';
import homeStyles from '../../styles/Home.module.css';
import Link from 'next/link';

export default function Layout({ children, home }) {
  return (
    <>
      <Head>
        <title>Projeto Insulina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.header}>
        <h1 className={homeStyles.logo}>Projeto insulina</h1>
        <navbar>
          <ul>
            <li className={homeStyles.listItem}>
              <Link href={`/cadastro`}>Cadastro</Link>
            </li>
            <li>
              <Link href={`/login`}>Login</Link>
            </li>
          </ul>
        </navbar>
      </header>
      <main>{children}</main>
      <footer className={styles.footer}>Footer</footer>
    </>
  );
}
